[project]
name = "rag-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhigyan Dey", email = "abhigyandey2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.1",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.3",
]

[project.scripts]
rag-from-scratch = "rag_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
